development: &development
  http:
    host: "0.0.0.0"
    port: 8081
  websocket:
    host: "0.0.0.0"
    port: 8080
  key: "key"
  secret: "secret"
  debug: true

production:
  <<: *development
  key: "key"
  secret: "secret"
  debug: false