development:
  host: "0.0.0.0"
  port: 8787
  key: "key"
  secret: "secret"
  debug: true

production:
  host: "0.0.0.0"
  port: 8787
  key: "PUT-SOME-UNIQ-CODE-HERE"
  secret: "topsecret"
  debug: false