development: &development
  http:
    host: "0.0.0.0"
    port: 8081
    debug: true
  websocket:
    host: "0.0.0.0"
    port: 8080
    debug: true
  key: "key"
  secret: "secret"

test:
  <<: *development
  
production:
  <<: *development
  key: "key"
  secret: "secret"