#!/usr/bin/env ruby
$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), '..', 'lib'))

require 'rubygems'
require 'daemons'
require 'prism'
require 'fileutils'

options = {
  :dir_mode   => :normal,
  :dir        => File.join(File.dirname(__FILE__), '..', 'tmp', 'pids'),
  :log_output => false,
  :backtrace  => true,
  :monitor    => true,
  :multiple    => false
}
Daemons.run(File.join(File.dirname(__FILE__), 'runner'), options)