#!/usr/bin/env ruby
$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), '..', 'lib'))

require 'rubygems'
require 'daemons'
require 'yaml'
require 'prism'

Daemons.run_proc('prism', :monitor => true) do
  if ARGV.include?('--')
    ARGV.slice! 0..ARGV.index('--')
  else
    ARGV.clear
  end
  
  config = YAML.load_file(File.join(File.dirname(__FILE__), '..', 'config', 'prism.yml'))[ARGV.first]
  
  Prism.start do |c|
    c.websocket = {
      :host  => config["websocket"]["host"],
      :port  => config["websocket"]["port"],
      :debug => config["websocket"]["debug"]
    }
    c.http = {
      :host  => config["http"]["host"],
      :port  => config["http"]["port"],
      :debug => config["http"]["debug"]
    }
    c.key    = config["key"]
    c.secret = config["secret"]
  end
end