#!/usr/bin/env ruby
$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), '..', 'lib'))

require 'rubygems'
require 'yaml'
require 'prism'

config = YAML.load_file(File.join(File.dirname(__FILE__), '..', 'config', 'prism.yml'))[ARGV.first]
p config
Prism.start do |c|
  c.host   = config["host"]
  c.port   = config["port"]
  c.key    = config["key"]
  c.secret = config["secret"]
  c.debug  = config["debug"]
end