#!/usr/bin/env ruby
$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), '..', 'lib'))

require 'rubygems'
require 'yaml'
require 'prism'

config = YAML.load_file(File.join(File.dirname(__FILE__), '..', 'config', 'prism.yml'))[ARGV.first]

Prism.start do |c|
  c.websocket = {
    :host  => config["websocket"]["host"],
    :port  => config["websocket"]["port"]
  }
  c.http = {
    :host  => config["http"]["host"],
    :port  => config["http"]["port"]
  }
  c.key    = config["key"]
  c.secret = config["secret"]
  c.debug  = config["debug"]
end